---
- name: Automatic Remediation of a webserver
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Say Hello
      condition: event.payload.message == "Test response"
      action:
        run_job_template:
          name: say-what.yml
